; Auto-generated. Do not edit!


(cl:in-package rover_msgs-srv)


;//! \htmlinclude WayPoints_srv_Tao-request.msg.html

(cl:defclass <WayPoints_srv_Tao-request> (roslisp-msg-protocol:ros-message)
  ((Start
    :reader Start
    :initarg :Start
    :type (cl:vector cl:float)
   :initform (cl:make-array 2 :element-type 'cl:float :initial-element 0.0))
   (Target
    :reader Target
    :initarg :Target
    :type (cl:vector cl:float)
   :initform (cl:make-array 2 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass WayPoints_srv_Tao-request (<WayPoints_srv_Tao-request>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <WayPoints_srv_Tao-request>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'WayPoints_srv_Tao-request)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rover_msgs-srv:<WayPoints_srv_Tao-request> is deprecated: use rover_msgs-srv:WayPoints_srv_Tao-request instead.")))

(cl:ensure-generic-function 'Start-val :lambda-list '(m))
(cl:defmethod Start-val ((m <WayPoints_srv_Tao-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rover_msgs-srv:Start-val is deprecated.  Use rover_msgs-srv:Start instead.")
  (Start m))

(cl:ensure-generic-function 'Target-val :lambda-list '(m))
(cl:defmethod Target-val ((m <WayPoints_srv_Tao-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rover_msgs-srv:Target-val is deprecated.  Use rover_msgs-srv:Target instead.")
  (Target m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <WayPoints_srv_Tao-request>) ostream)
  "Serializes a message object of type '<WayPoints_srv_Tao-request>"
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Start))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Target))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <WayPoints_srv_Tao-request>) istream)
  "Deserializes a message object of type '<WayPoints_srv_Tao-request>"
  (cl:setf (cl:slot-value msg 'Start) (cl:make-array 2))
  (cl:let ((vals (cl:slot-value msg 'Start)))
    (cl:dotimes (i 2)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'Target) (cl:make-array 2))
  (cl:let ((vals (cl:slot-value msg 'Target)))
    (cl:dotimes (i 2)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<WayPoints_srv_Tao-request>)))
  "Returns string type for a service object of type '<WayPoints_srv_Tao-request>"
  "rover_msgs/WayPoints_srv_TaoRequest")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WayPoints_srv_Tao-request)))
  "Returns string type for a service object of type 'WayPoints_srv_Tao-request"
  "rover_msgs/WayPoints_srv_TaoRequest")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<WayPoints_srv_Tao-request>)))
  "Returns md5sum for a message object of type '<WayPoints_srv_Tao-request>"
  "f979d4bef44161c3de0eaa389ab41bd3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'WayPoints_srv_Tao-request)))
  "Returns md5sum for a message object of type 'WayPoints_srv_Tao-request"
  "f979d4bef44161c3de0eaa389ab41bd3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<WayPoints_srv_Tao-request>)))
  "Returns full string definition for message of type '<WayPoints_srv_Tao-request>"
  (cl:format cl:nil "float64[2] Start~%float64[2] Target~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'WayPoints_srv_Tao-request)))
  "Returns full string definition for message of type 'WayPoints_srv_Tao-request"
  (cl:format cl:nil "float64[2] Start~%float64[2] Target~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <WayPoints_srv_Tao-request>))
  (cl:+ 0
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'Start) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'Target) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <WayPoints_srv_Tao-request>))
  "Converts a ROS message object to a list"
  (cl:list 'WayPoints_srv_Tao-request
    (cl:cons ':Start (Start msg))
    (cl:cons ':Target (Target msg))
))
;//! \htmlinclude WayPoints_srv_Tao-response.msg.html

(cl:defclass <WayPoints_srv_Tao-response> (roslisp-msg-protocol:ros-message)
  ((X
    :reader X
    :initarg :X
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (Y
    :reader Y
    :initarg :Y
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (Width
    :reader Width
    :initarg :Width
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass WayPoints_srv_Tao-response (<WayPoints_srv_Tao-response>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <WayPoints_srv_Tao-response>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'WayPoints_srv_Tao-response)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rover_msgs-srv:<WayPoints_srv_Tao-response> is deprecated: use rover_msgs-srv:WayPoints_srv_Tao-response instead.")))

(cl:ensure-generic-function 'X-val :lambda-list '(m))
(cl:defmethod X-val ((m <WayPoints_srv_Tao-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rover_msgs-srv:X-val is deprecated.  Use rover_msgs-srv:X instead.")
  (X m))

(cl:ensure-generic-function 'Y-val :lambda-list '(m))
(cl:defmethod Y-val ((m <WayPoints_srv_Tao-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rover_msgs-srv:Y-val is deprecated.  Use rover_msgs-srv:Y instead.")
  (Y m))

(cl:ensure-generic-function 'Width-val :lambda-list '(m))
(cl:defmethod Width-val ((m <WayPoints_srv_Tao-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rover_msgs-srv:Width-val is deprecated.  Use rover_msgs-srv:Width instead.")
  (Width m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <WayPoints_srv_Tao-response>) ostream)
  "Serializes a message object of type '<WayPoints_srv_Tao-response>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'X))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'X))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Y))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Y))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Width))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Width))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <WayPoints_srv_Tao-response>) istream)
  "Deserializes a message object of type '<WayPoints_srv_Tao-response>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'X) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'X)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Y) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Y)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Width) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Width)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<WayPoints_srv_Tao-response>)))
  "Returns string type for a service object of type '<WayPoints_srv_Tao-response>"
  "rover_msgs/WayPoints_srv_TaoResponse")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WayPoints_srv_Tao-response)))
  "Returns string type for a service object of type 'WayPoints_srv_Tao-response"
  "rover_msgs/WayPoints_srv_TaoResponse")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<WayPoints_srv_Tao-response>)))
  "Returns md5sum for a message object of type '<WayPoints_srv_Tao-response>"
  "f979d4bef44161c3de0eaa389ab41bd3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'WayPoints_srv_Tao-response)))
  "Returns md5sum for a message object of type 'WayPoints_srv_Tao-response"
  "f979d4bef44161c3de0eaa389ab41bd3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<WayPoints_srv_Tao-response>)))
  "Returns full string definition for message of type '<WayPoints_srv_Tao-response>"
  (cl:format cl:nil "float64[] X~%float64[] Y~%float64[] Width~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'WayPoints_srv_Tao-response)))
  "Returns full string definition for message of type 'WayPoints_srv_Tao-response"
  (cl:format cl:nil "float64[] X~%float64[] Y~%float64[] Width~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <WayPoints_srv_Tao-response>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'X) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Y) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Width) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <WayPoints_srv_Tao-response>))
  "Converts a ROS message object to a list"
  (cl:list 'WayPoints_srv_Tao-response
    (cl:cons ':X (X msg))
    (cl:cons ':Y (Y msg))
    (cl:cons ':Width (Width msg))
))
(cl:defmethod roslisp-msg-protocol:service-request-type ((msg (cl:eql 'WayPoints_srv_Tao)))
  'WayPoints_srv_Tao-request)
(cl:defmethod roslisp-msg-protocol:service-response-type ((msg (cl:eql 'WayPoints_srv_Tao)))
  'WayPoints_srv_Tao-response)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WayPoints_srv_Tao)))
  "Returns string type for a service object of type '<WayPoints_srv_Tao>"
  "rover_msgs/WayPoints_srv_Tao")