// Generated by gencpp from file rover_msgs/WayPoints_srv_Tao.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_WAYPOINTS_SRV_TAO_H
#define ROVER_MSGS_MESSAGE_WAYPOINTS_SRV_TAO_H

#include <ros/service_traits.h>


#include <rover_msgs/WayPoints_srv_TaoRequest.h>
#include <rover_msgs/WayPoints_srv_TaoResponse.h>


namespace rover_msgs
{

struct WayPoints_srv_Tao
{

typedef WayPoints_srv_TaoRequest Request;
typedef WayPoints_srv_TaoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WayPoints_srv_Tao
} // namespace rover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rover_msgs::WayPoints_srv_Tao > {
  static const char* value()
  {
    return "f979d4bef44161c3de0eaa389ab41bd3";
  }

  static const char* value(const ::rover_msgs::WayPoints_srv_Tao&) { return value(); }
};

template<>
struct DataType< ::rover_msgs::WayPoints_srv_Tao > {
  static const char* value()
  {
    return "rover_msgs/WayPoints_srv_Tao";
  }

  static const char* value(const ::rover_msgs::WayPoints_srv_Tao&) { return value(); }
};


// service_traits::MD5Sum< ::rover_msgs::WayPoints_srv_TaoRequest> should match
// service_traits::MD5Sum< ::rover_msgs::WayPoints_srv_Tao >
template<>
struct MD5Sum< ::rover_msgs::WayPoints_srv_TaoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rover_msgs::WayPoints_srv_Tao >::value();
  }
  static const char* value(const ::rover_msgs::WayPoints_srv_TaoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rover_msgs::WayPoints_srv_TaoRequest> should match
// service_traits::DataType< ::rover_msgs::WayPoints_srv_Tao >
template<>
struct DataType< ::rover_msgs::WayPoints_srv_TaoRequest>
{
  static const char* value()
  {
    return DataType< ::rover_msgs::WayPoints_srv_Tao >::value();
  }
  static const char* value(const ::rover_msgs::WayPoints_srv_TaoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rover_msgs::WayPoints_srv_TaoResponse> should match
// service_traits::MD5Sum< ::rover_msgs::WayPoints_srv_Tao >
template<>
struct MD5Sum< ::rover_msgs::WayPoints_srv_TaoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rover_msgs::WayPoints_srv_Tao >::value();
  }
  static const char* value(const ::rover_msgs::WayPoints_srv_TaoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rover_msgs::WayPoints_srv_TaoResponse> should match
// service_traits::DataType< ::rover_msgs::WayPoints_srv_Tao >
template<>
struct DataType< ::rover_msgs::WayPoints_srv_TaoResponse>
{
  static const char* value()
  {
    return DataType< ::rover_msgs::WayPoints_srv_Tao >::value();
  }
  static const char* value(const ::rover_msgs::WayPoints_srv_TaoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_WAYPOINTS_SRV_TAO_H
